<?php
namespace Database\Seeders;
 use Illuminate\Database\Seeder;
 use App\Models\Place;
 use Illuminate\Support\Facades\DB;

    class PlaceSeeder extends Seeder
    {
        public function run()
        {
    // Datos de la base de datos

            $places = [

                [
        'name' => 'Hotel Intercontinental Medellín',
        'description' => 'Hotel lujoso con vistas panorámicas de la ciudad.',
        'location' => 'Antoquia', // Asegúrate de incluir esta línea
        'climate' => 'Nublado', // Asegúrate de incluir este campo
        'image_url' => 'https://www.intercontinental.com/images/hotel1.jpg',
        'video_url' => 'https://www.youtube.com/watch?v=example',
        'google_maps' => 'https://www.google.com/maps/place/Hotel+Intercontinental',
        'category' => 'hotel',
        'latitude' => 6.25,
        'longitude' => -75.574,
        'services' => json_encode(['piscina', 'gimnasio', 'spa']),
        'price_per_night' => 200,
        'phone_number' => '0345678901',
        'email' => 'info@intercontinental.com',
        'website' => 'https://www.intercontinental.com',
        'capacity' => 150,
        'rating' => 5,
        'address' => 'Calle 1 # 2-3',
        'city' => 'Medellín',
        'created_at' => now(),
        'updated_at' => now()
    ],[
            'name' => 'Hotel Intercontinental Medellín',
            'description' => 'Hotel lujoso con vistas panorámicas de la ciudad.',
            'location' => 'Antoquia',
            'climate' => 'Nublado',
            'image_url' => 'https://www.intercontinental.com/images/hotel1.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example',
            'google_maps' => 'https://www.google.com/maps/place/Hotel+Intercontinental',
            'category' => 'Hotel', // Asegúrate de que esta columna tenga un valor
            'latitude' => 6.25,
            'longitude' => -75.574,
            'services' => json_encode(["piscina", "gimnasio", "spa"]), // Asegúrate de codificarlo si es necesario
            'price_per_night' => 200,
            'phone_number' => '0345678901',
            'email' => 'info@intercontinental.com',
            'website' => 'https://www.intercontinental.com',
            'capacity' => 150,
            'rating' => 5,
            'address' => 'Calle 1 # 2-3',
            'city' => 'Medellín',
            'created_at' => now(),
            'updated_at' => now()
        ],

    // Mejores Lugares Turísticos Parques hoteles centro de relajacon spas centro de bienestar 
                [
            'name' => 'Parque Arví',
            'description' => 'Reserva natural ideal para caminatas y actividades al aire libre.',
            'location' => 'Medellín',
            'climate' => 'Templado',
            'image_url' => 'https://www.parquearvi.com/images/park.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example21',
            'google_maps' => 'https://www.google.com/maps/place/Parque+Arví',
            'category' => 'tourist',
            'latitude' => 6.2176,
            'longitude' => -75.5301,
        ],
    [
                    
                    'name' => 'Guatapé',
                    'description' => 'Pueblo famoso por su colorido y la Piedra del Peñol.',
                    'location' => 'Guatapé',
                    'climate' => 'Templado',
                    'image_url' => 'https://www.guatape.com.co/images/guatape.jpg',
                    'video_url' => 'https://www.youtube.com/watch?v=example11',
                    'google_maps' => 'https://www.google.com/maps/place/Guatapé',
                    'category' => 'tourist',
                    'latitude' => 6.0035,
                    'longitude' => -75.1558
                ],
                [
                    
                    'name' => 'Museo de Antioquia',
                    'description' => 'Museo con una rica colección de arte moderno y contemporáneo.',
                    'location' => 'Medellín',
                    'climate' => 'Templado',
                    'image_url' => 'https://www.museodeantioquia.com/images/museum.jpg',
                    'video_url' => 'https://www.youtube.com/watch?v=example11',
                    'google_maps' => 'https://www.google.com/maps/place/Museo+de+Antioquia',
                    'category' => 'tourist',
                    'latitude' => 6.2518,
                    'longitude' => -75.5636
                ],
                [
                
                    'name' => 'Jardín Botánico',
                    'description' => 'Espacio verde con una gran variedad de flora y un ambiente tranquilo.',
                    'location' => 'Medellín',
                    'climate' => 'Templado',
                    'image_url' => 'https://www.jardinbotanico.com/images/garden.jpg',
                    'video_url' => 'https://www.youtube.com/watch?v=example11',
                    'google_maps' => 'https://www.google.com/maps/place/Jard%C3%ADn+Bot%C3%A1nico+de+Medell%C3%ADn',
                    'category' => 'tourist',
                    'latitude' => 6.2434,
                    'longitude' => -75.5737
                ],
                [
                    
                    'name' => 'Metrocable',
                    'description' => 'Transporte público que ofrece vistas panorámicas de la ciudad.',
                    'location' => 'Medellín',
                    'climate' => 'Templado',
                    'image_url' => 'https://www.metrocable.com/images/metrocable.jpg',
                    'video_url' => 'https://www.youtube.com/watch?v=example11',
                    'google_maps' => 'https://www.google.com/maps/place/Metrocable',
                    'category' => 'tourist',
                    'latitude' => 6.2542,
                    'longitude' => -75.5905
                ],
                [
                    
                    'name' => 'Pueblo Viejo',
                    'description' => 'Un sitio turístico que representa la cultura antioqueña.',
                    'location' => 'Medellín',
                    'climate' => 'Templado',
                    'image_url' => 'https://www.puebloviejo.com/images/pueblo.jpg',
                    'video_url' => 'https://www.youtube.com/watch?v=example11',
                    'google_maps' => 'https://www.google.com/maps/place/Pueblo+Viejo',
                    'category' => 'tourist',
                    'latitude' => 6.2304,
                    'longitude' => -75.5910
                ],
                [
                    
                    'name' => 'Plaza Botero',
                    'description' => 'Plaza famosa por sus esculturas del artista Fernando Botero.',
                    'location' => 'Medellín',
                    'climate' => 'Templado',
                    'image_url' => 'https://www.plazabotero.com/images/plaza.jpg',
                    'video_url' => 'https://www.youtube.com/watch?v=example11',
                    'google_maps' => 'https://www.google.com/maps/place/Plaza+Botero',
                    'category' => 'tourist',
                    'latitude' => 6.2476,
                    'longitude' => -75.5753
                ],
                [
                    
                    'name' => 'Parque de los Deseos',
                    'description' => 'Parque popular que ofrece cine al aire libre y eventos culturales.',
                    'location' => 'Medellín',
                    'climate' => 'Templado',
                    'image_url' => 'https://www.parquedeldeseos.com/images/park.jpg',
                    'video_url' => 'https://www.youtube.com/watch?v=example11',
                    'google_maps' => 'https://www.google.com/maps/place/Parque+de+los+Deseos',
                    'category' => 'tourist',
                    'latitude' => 6.2519,
                    'longitude' => -75.5698
                ],
                [
                    
                    'name' => 'El Peñol',
                    'description' => 'Monumento natural y mirador con impresionantes vistas.',
                    'location' => 'Guatapé',
                    'climate' => 'Templado',
                    'image_url' => 'https://www.elpenol.com/images/rock.jpg',
                    'video_url' => 'https://www.youtube.com/watch?v=example11',
                    'google_maps' => 'https://www.google.com/maps/place/El+Pe%C3%B1ol',
                    'category' => 'tourist',
                    'latitude' => 6.0434,
                    'longitude' => -75.1564
                ],
                [
                    
                    'name' => 'Parque Explora',
                    'description' => 'Parque interactivo de ciencia y tecnología ideal para familias.',
                    'location' => 'Medellín',
                    'climate' => 'Templado',
                    'image_url' => 'https://www.parqueexplora.com/images/explora.jpg',
                    'video_url' => 'https://www.youtube.com/watch?v=example11',
                    'google_maps' => 'https://www.google.com/maps/place/Parque+Explora',
                    'category' => 'tourist',
                    'latitude' => 6.2462,
                    'longitude' => -75.5797
                ],//
                
                //Mejores Lugares de Relajacon       
        [
            
            'name' => 'Parque Arví',
            'description' => 'Reserva natural ideal para caminatas y picnic.',
            'location' => 'Medellín',
            'image_url' => 'https://www.parquearvi.com/images/relaxation1.jpg',
            'google_maps' => 'https://www.google.com/maps/place/Parque+Arv%C3%AD',
            'category' => 'relaxation',
            'climate' => 'Tropical',
            'latitude' => 6.1828,
            'longitude' => -75.4858,
            'services' => json_encode(['caminatas', 'picnic']),
            'opening_time' => '08:00:00',
            'closing_time' => '17:00:00',
            'price_range' => 0.00,
            'contact_number' => '0123456789',
            'email' => 'info@parquearvi.com',
        ],
        [
            
            'name' => 'Jardín Botánico',
            'description' => 'Hermosos jardines y senderos para relajarse.',
            'location' => 'Medellín',
            'image_url' => 'https://www.jardinbotanico.com/images/relaxation2.jpg',
            'google_maps' => 'https://www.google.com/maps/place/Jard%C3%ADn+Bot%C3%A1nico',
            'category' => 'relaxation',
            'climate' => 'Tropical',
            'latitude' => 6.2482,
            'longitude' => -75.5726,
            'services' => json_encode(['senderos', 'jardines']),
            'opening_time' => '09:00:00',
            'closing_time' => '18:00:00',
            'price_range' => 0.00,
            'contact_number' => '0987654321',
            'email' => 'info@jardinbotanico.com',
        ],
        [
            
            'name' => 'Parque de los Deseos',
            'description' => 'Espacio cultural y recreativo en la ciudad.',
            'location' => 'Medellín',
            'image_url' => 'https://www.parquededeseos.com/images/relaxation3.jpg',
            'google_maps' => 'https://www.google.com/maps/place/Parque+de+los+Deseos',
            'category' => 'relaxation',
            'climate' => 'Tropical',
            'latitude' => 6.2515,
            'longitude' => -75.5764,
            'services' => json_encode(['cultural events', 'recreación']),
            'opening_time' => '10:00:00',
            'closing_time' => '21:00:00',
            'price_range' => 0.00,
            'contact_number' => '0345678901',
            'email' => 'info@parquededeseos.com',
        ],
        [
            
            'name' => 'Cerro Nutibara',
            'description' => 'Mirador con vistas panorámicas de la ciudad.',
            'location' => 'Medellín',
            'image_url' => 'https://www.cerrounitibara.com/images/relaxation4.jpg',
            'google_maps' => 'https://www.google.com/maps/place/Cerro+Nutibara',
            'category' => 'relaxation',
            'climate' => 'Tropical',
            'latitude' => 6.2612,
            'longitude' => -75.5758,
            'services' => json_encode(['mirador', 'senderos']),
            'opening_time' => '06:00:00',
            'closing_time' => '19:00:00',
            'price_range' => 0.00,
            'contact_number' => '0345678902',
            'email' => 'info@cerrounitibara.com',
        ],
        [
            
            'name' => 'Parque El Poblado',
            'description' => 'Un espacio verde en medio de la ciudad.',
            'location' => 'Medellín',
            'image_url' => 'https://www.parqueelpoblado.com/images/relaxation5.jpg',
            'google_maps' => 'https://www.google.com/maps/place/Parque+El+Poblado',
            'category' => 'relaxation',
            'climate' => 'Tropical',
            'latitude' => 6.2116,
            'longitude' => -75.5706,
            'services' => json_encode(['senderos', 'áreas de descanso']),
            'opening_time' => '06:00:00',
            'closing_time' => '22:00:00',
            'price_range' => 0.00,
            'contact_number' => '0345678903',
            'email' => 'info@parqueelpoblado.com',
        ],
        [
            
            'name' => 'Reserva Natural Cañón del Río Claro',
            'description' => 'Espacio natural para el ecoturismo y la relajación.',
            'location' => 'Cañón del Río Claro',
            'image_url' => 'https://www.canyonrio.com/images/relaxation6.jpg',
            'google_maps' => 'https://www.google.com/maps/place/Reserva+Natural+C%C3%A1non+del+R%C3%ADo+Claro',
            'category' => 'relaxation',
            'climate' => 'Tropical',
            'latitude' => 6.1750,
            'longitude' => -75.6130,
            'services' => json_encode(['ecoturismo', 'senderos']),
            'opening_time' => '08:00:00',
            'closing_time' => '17:00:00',
            'price_range' => 10.00,
            'contact_number' => '0345678904',
            'email' => 'info@canyondelrioclaro.com',
        ],
        [
        
            'name' => 'Laguna de Guatapé',
            'description' => 'Un hermoso lago ideal para la recreación y el descanso.',
            'location' => 'Guatapé',
            'image_url' => 'https://www.lagunaguatape.com/images/relaxation7.jpg',
            'google_maps' => 'https://www.google.com/maps/place/Laguna+de+Guatap%C3%A9',
            'category' => 'relaxation',
            'climate' => 'Tropical',
            'latitude' => 6.0422,
            'longitude' => -75.1665,
            'services' => json_encode(['navegación', 'paseos']),
            'opening_time' => '08:00:00',
            'closing_time' => '18:00:00',
            'price_range' => 15.00,
            'contact_number' => '0345678905',
            'email' => 'info@lagunaguatape.com',
        ],
        [
            
            'name' => 'Cascada La Honda',
            'description' => 'Un lugar tranquilo rodeado de naturaleza.',
            'location' => 'San Carlos',
            'image_url' => 'https://www.cascadalahonda.com/images/relaxation8.jpg',
            'google_maps' => 'https://www.google.com/maps/place/Cascada+La+Honda',
            'category' => 'relaxation',
            'climate' => 'Tropical',
            'latitude' => 5.7576,
            'longitude' => -75.6348,
            'services' => json_encode(['senderos', 'picnic']),
            'opening_time' => '08:00:00',
            'closing_time' => '17:00:00',
            'price_range' => 0.00,
            'contact_number' => '0345678906',
            'email' => 'info@cascadalahonda.com',
        ],
        [
            
            'name' => 'Termales de Santa Rosa',
            'description' => 'Aguas termales perfectas para relajarse.',
            'location' => 'Santa Rosa de Cabal',
            'image_url' => 'https://www.termalessantarosa.com/images/relaxation9.jpg',
            'google_maps' => 'https://www.google.com/maps/place/Termales+de+Santa+Rosa',
            'category' => 'relaxation',
            'climate' => 'Tropical',
            'latitude' => 5.2645,
            'longitude' => -75.6337,
            'services' => json_encode(['aguas termales', 'masajes']),
            'opening_time' => '09:00:00',
            'closing_time' => '21:00:00',
            'price_range' => 30.00,
            'contact_number' => '0345678907',
            'email' => 'info@termalessantarosa.com',
        ],
        [
            
            'name' => 'Spa del Parque',
            'description' => 'Spa y centro de bienestar en un entorno natural.',
            'location' => 'Medellín',
            'image_url' => 'https://www.spadelparque.com/images/relaxation10.jpg',
            'google_maps' => 'https://www.google.com/maps/place/Spa+del+Parque',
            'category' => 'relaxation',
            'climate' => 'Tropical',
            'latitude' => 6.2500,
            'longitude' => -75.5740,
            'services' => json_encode(['masajes', 'tratamientos de spa']),
            'opening_time' => '10:00:00',
            'closing_time' => '20:00:00',
            'price_range' => 50.00,
            'contact_number' => '0345678908',
            'email' => 'info@spadelparque.com',
        ],

    //  Mejores Hoteles
                [
                    
                    'name' => 'Hotel Intercontinental Medellín',
                    'description' => 'Hotel lujoso con vistas panorámicas de la ciudad.',
                    'address' => 'Calle 1 # 2-3',
                    'city' => 'Medellín',
                    'rating' => 5,
                    'price_per_night' => 200.00,
                    'phone_number' => '0345678901',
                    'email' => 'info@intercontinental.com',
                    'website' => 'https://www.intercontinental.com',
                    'capacity' => 150,
                    'services' => json_encode(['piscina', 'gimnasio', 'spa']),
                    'image_url' => 'https://www.intercontinental.com/images/hotel1.jpg',
                    'latitude' => 6.2500,
                    'longitude' => -75.5740,
                    'category' => 'hotel',
                ],
                [
                    
                    'name' => 'Hotel Estelar Milla de Oro',
                    'description' => 'Hotel moderno ubicado en una de las zonas más exclusivas de Medellín.',
                    'address' => 'Carrera 43A # 1-15',
                    'city' => 'Medellín',
                    'rating' => 4,
                    'price_per_night' => 150.00,
                    'phone_number' => '0345678902',
                    'email' => 'info@estelarmilladeoro.com',
                    'website' => 'https://www.estelarmilladeoro.com',
                    'capacity' => 120,
                    'services' => json_encode(['restaurante', 'salones de eventos']),
                    'image_url' => 'https://www.estelarmilladeoro.com/images/hotel2.jpg',
                    'latitude' => 6.2501,
                    'longitude' => -75.5741,
                    'category' => 'hotel',
                ],
                [
                    
                    'name' => 'Hotel Dann Carlton Medellín',
                    'description' => 'Hotel elegante que ofrece un excelente servicio y comodidad.',
                    'address' => 'Calle 2 # 4-10',
                    'city' => 'Medellín',
                    'rating' => 4,
                    'price_per_night' => 180.00,
                    'phone_number' => '0345678903',
                    'email' => 'info@danncarlton.com',
                    'website' => 'https://www.danncarlton.com',
                    'capacity' => 100,
                    'services' => json_encode(['wifi gratis', 'sala de reuniones']),
                    'image_url' => 'https://www.danncarlton.com/images/hotel.jpg',
                    'latitude' => 6.2502,
                    'longitude' => -75.5742,
                    'category' => 'hotel',
                ],
                [
                    
                    'name' => 'The Charlee Hotel',
                    'description' => 'Hotel boutique con un enfoque en el arte y la cultura.',
                    'address' => 'Calle 9 # 4-22',
                    'city' => 'Medellín',
                    'rating' => 4,
                    'price_per_night' => 250.00,
                    'phone_number' => '0345678904',
                    'email' => 'info@thecharlee.com',
                    'website' => 'https://www.thecharlee.com',
                    'capacity' => 80,
                    'services' => json_encode(['piscina en la azotea', 'bar']),
                    'image_url' => 'https://www.thecharlee.com/images/hotel.jpg',
                    'latitude' => 6.2503,
                    'longitude' => -75.5743,
                    'category' => 'hotel',
                ],
                [
                    
                    'name' => 'Hotel San Fernando Plaza',
                    'description' => 'Hotel moderno con amplias habitaciones y excelentes servicios.',
                    'address' => 'Calle 10 # 4-15',
                    'city' => 'Medellín',
                    'rating' => 4,
                    'price_per_night' => 160.00,
                    'phone_number' => '0345678905',
                    'email' => 'info@sanfernandoplaza.com',
                    'website' => 'https://www.sanfernandoplaza.com',
                    'capacity' => 140,
                    'services' => json_encode(['spa', 'restaurante']),
                    'image_url' => 'https://www.sanfernandoplaza.com/images/hotel.jpg',
                    'latitude' => 6.2504,
                    'longitude' => -75.5744,
                    'category' => 'hotel',
                ],
                [
                    
                    'name' => 'Hotel Miami',
                    'description' => 'Hotel sencillo y cómodo en una buena ubicación.',
                    'address' => 'Calle 5 # 4-18',
                    'city' => 'Medellín',
                    'rating' => 3,
                    'price_per_night' => 80.00,
                    'phone_number' => '0345678906',
                    'email' => 'info@hotelmiami.com',
                    'website' => 'https://www.hotelmiami.com',
                    'capacity' => 60,
                    'services' => json_encode(['wifi gratis']),
                    'image_url' => 'https://www.hotelmiami.com/images/hotel.jpg',
                    'latitude' => 6.2505,
                    'longitude' => -75.5745,
                    'category' => 'hotel',
                ],
                [
                    
                    'name' => 'Hotel La Playa',
                    'description' => 'Un hotel económico ideal para viajeros.',
                    'address' => 'Calle 6 # 4-20',
                    'city' => 'Medellín',
                    'rating' => 3,
                    'price_per_night' => 70.00,
                    'phone_number' => '0345678907',
                    'email' => 'info@hotellaplaya.com',
                    'website' => 'https://www.hotellaplaya.com',
                    'capacity' => 50,
                    'services' => json_encode(['desayuno incluido']),
                    'image_url' => 'https://www.hotellaplaya.com/images/hotel.jpg',
                    'latitude' => 6.2506,
                    'longitude' => -75.5746,
                    'category' => 'hotel',
                ],
                [
                    
                    'name' => 'Hotel Boutique Casa Rossa',
                    'description' => 'Un hotel boutique encantador con un diseño único.',
                    'address' => 'Calle 8 # 4-12',
                    'city' => 'Medellín',
                    'rating' => 4,
                    'price_per_night' => 120.00,
                    'phone_number' => '0345678908',
                    'email' => 'info@casarossa.com',
                    'website' => 'https://www.casarossa.com',
                    'capacity' => 30,
                    'services' => json_encode(['café', 'artículos de tocador gratis']),
                    'image_url' => 'https://www.casarossa.com/images/hotel.jpg',
                    'latitude' => 6.2507,
                    'longitude' => -75.5747,
                    'category' => 'hotel',
                ],
                [
                
                    'name' => 'Hotel Casa Blanca',
                    'description' => 'Hotel acogedor con un ambiente familiar.',
                    'address' => 'Calle 3 # 5-15',
                    'city' => 'Medellín',
                    'rating' => 4,
                    'price_per_night' => 90.00,
                    'phone_number' => '0345678909',
                    'email' => 'info@hotelcasablanca.com',
                    'website' => 'https://www.hotelcasablanca.com',
                    'capacity' => 40,
                    'services' => json_encode(['salón de eventos', 'wifi gratis']),
                    'image_url' => 'https://www.hotelcasablanca.com/images/hotel.jpg',
                    'latitude' => 6.2508,
                    'longitude' => -75.5748,
                    'category' => 'hotel',
                ],
                [
                    
                    'name' => 'Hotel Nutibara',
                    'description' => 'Hotel histórico en el corazón de Medellín.',
                    'address' => 'Carrera 52 # 52-10',
                    'city' => 'Medellín',
                    'rating' => 3,
                    'price_per_night' => 85.00,
                    'phone_number' => '0345678910',
                    'email' => 'info@hotelnutibara.com',
                    'website' => 'https://www.hotelnutibara.com',
                    'capacity' => 70,
                    'services' => json_encode(['restaurante', 'bar']),
                    'image_url' => 'https://www.hotelnutibara.com/images/hotel.jpg',
                    'latitude' => 6.2509,
                    'longitude' => -75.5749,
                    'category' => 'hotel',
                ],
                // Datos de las gastronomías lugares platos tpcos restaurantes cafe 
            
        [
            
            'name' => 'Bandeja Paisa',
            'description' => 'Plato típico de Antioquia con frijoles, carne, plátano y más.',
            'location' => 'Antioquia',
            'image_url' => 'https://www.gastronomiapaisa.com/images/gastronomy1.jpg',
            'google_maps' => 'https://www.google.com/maps/place/Bandeja+Paisa',
            'category' => 'gastronomy',
            'latitude' => 6.2442, // Latitud real
            'longitude' => -75.5812, // Longitud real
            'video_url' => 'https://www.youtube.com/watch?v=example1' // URL de video
        ],
        [
            
            'name' => 'Arepas',
            'description' => 'Deliciosas arepas de maíz, acompañadas de varios ingredientes.',
            'location' => 'Antioquia',
            'image_url' => 'https://www.gastronomiapaisa.com/images/gastronomy2.jpg',
            'google_maps' => 'https://www.google.com/maps/place/Arepas',
            'category' => 'gastronomy',
            'latitude' => 6.2442,
            'longitude' => -75.5812,
            'video_url' => 'https://www.youtube.com/watch?v=example2'
        ],
        [
            
            'name' => 'Sancocho',
            'description' => 'Sopa tradicional a base de yuca, plátano y carne.',
            'location' => 'Antioquia',
            'image_url' => 'https://www.gastronomiapaisa.com/images/gastronomy3.jpg',
            'google_maps' => 'https://www.google.com/maps/place/Sancocho',
            'category' => 'gastronomy',
            'latitude' => 6.2442,
            'longitude' => -75.5812,
            'video_url' => 'https://www.youtube.com/watch?v=example3'
        ],
        [
            
            'name' => 'Tamales',
            'description' => 'Plato hecho con masa de maíz y relleno de carne y vegetales.',
            'location' => 'Antioquia',
            'image_url' => 'https://www.gastronomiapaisa.com/images/gastronomy4.jpg',
            'google_maps' => 'https://www.google.com/maps/place/Tamales',
            'category' => 'gastronomy',
            'latitude' => 6.2442,
            'longitude' => -75.5812,
            'video_url' => 'https://www.youtube.com/watch?v=example4'
        ],
        [
            
            'name' => 'Buñuelos',
            'description' => 'Bollos fritos de masa de queso, perfectos para acompañar.',
            'location' => 'Antioquia',
            'image_url' => 'https://www.gastronomiapaisa.com/images/gastronomy5.jpg',
            'google_maps' => 'https://www.google.com/maps/place/Bu%C3%B1uelos',
            'category' => 'gastronomy',
            'latitude' => 6.2442,
            'longitude' => -75.5812,
            'video_url' => 'https://www.youtube.com/watch?v=example5'
        ],
        [
            
            'name' => 'Empanadas',
            'description' => 'Deliciosas empanadas rellenas de carne o pollo.',
            'location' => 'Antioquia',
            'image_url' => 'https://www.gastronomiapaisa.com/images/gastronomy6.jpg',
            'google_maps' => 'https://www.google.com/maps/place/Empanadas',
            'category' => 'gastronomy',
            'latitude' => 6.2442,
            'longitude' => -75.5812,
            'video_url' => 'https://www.youtube.com/watch?v=example6'
        ],
        [
            
            'name' => 'Posta Negra',
            'description' => 'Carne de res en salsa de panela, un deleite para el paladar.',
            'location' => 'Antioquia',
            'image_url' => 'https://www.gastronomiapaisa.com/images/gastronomy7.jpg',
            'google_maps' => 'https://www.google.com/maps/place/Posta+Negra',
            'category' => 'gastronomy',
            'latitude' => 6.2442,
            'longitude' => -75.5812,
            'video_url' => 'https://www.youtube.com/watch?v=example7'
        ],
        [
            
            'name' => 'Ajiaco',
            'description' => 'Sopa tradicional con pollo, maíz y papas.',
            'location' => 'Antioquia',
            'image_url' => 'https://www.gastronomiapaisa.com/images/gastronomy8.jpg',
            'google_maps' => 'https://www.google.com/maps/place/Ajiaco',
            'category' => 'gastronomy',
            'latitude' => 6.2442,
            'longitude' => -75.5812,
            'video_url' => 'https://www.youtube.com/watch?v=example8'
        ],
        [
            
            'name' => 'Chocoramo',
            'description' => 'Delicia de galleta con chocolate y relleno de marshmallow.',
            'location' => 'Antioquia',
            'image_url' => 'https://www.gastronomiapaisa.com/images/gastronomy9.jpg',
            'google_maps' => 'https://www.google.com/maps/place/Chocoramo',
            'category' => 'gastronomy',
            'latitude' => 6.2442,
            'longitude' => -75.5812,
            'video_url' => 'https://www.youtube.com/watch?v=example9'
        ],
        [
            
            'name' => 'Tinto',
            'description' => 'Café negro, una tradición antioqueña.',
            'location' => 'Antioquia',
            'image_url' => 'https://www.gastronomiapaisa.com/images/gastronomy10.jpg',
            'google_maps' => 'https://www.google.com/maps/place/Tinto',
            'category' => 'gastronomy',
            'latitude' => 6.2442,
            'longitude' => -75.5812,
            'video_url' => 'https://www.youtube.com/watch?v=example10'
        ],
    //Mejores Restaurants 
        [
            
            'name' => 'El Cielo Medellín',
            'description' => 'Restaurante de alta cocina con un enfoque en la experiencia sensorial.',
            'location' => 'Medellín',
            'climate' => 'Templado',
            'image_url' => 'https://www.elcielorestaurant.com/images/restaurant.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example11',
            'google_maps' => 'https://www.google.com/maps/place/Restaurante+El+Cielo',
            'latitude' => 6.2300,
            'longitude' => -75.5900,
            'phone_number' => '1234567890',
            'email' => 'info@elcielo.com',
            'website' => 'https://www.elcielorestaurant.com',
            'average_price' => 80.00,
            'menu' => json_encode(['plato1' => 'Filete Mignon', 'plato2' => 'Sopa de Trufa']),
            'services' => json_encode(['Delivery', 'Reservas']),
            'category' => 'restaurant',
            'rating' => 4.5,
        ],
        [
            
            'name' => 'Hacienda Junín',
            'description' => 'Restaurante tradicional que ofrece platos típicos antioqueños.',
            'location' => 'Medellín',
            'climate' => 'Templado',
            'image_url' => 'https://www.hacienda-junin.com/images/restaurant.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example12',
            'google_maps' => 'https://www.google.com/maps/place/Hacienda+Junín',
            'latitude' => 6.2500,
            'longitude' => -75.5700,
            'phone_number' => '0987654321',
            'email' => 'info@haciendajunin.com',
            'website' => 'https://www.haciendajunin.com',
            'average_price' => 50.00,
            'menu' => json_encode(['plato1' => 'Bandeja Paisa', 'plato2' => 'Sancocho']),
            'services' => json_encode(['Delivery', 'Reservas']),
            'category' => 'restaurant',
            'rating' => 4.0,
        ],
        [
            
            'name' => 'Restaurante La Pampa',
            'description' => 'Carnes a la parrilla en un ambiente acogedor.',
            'location' => 'Medellín',
            'climate' => 'Tropical',
            'image_url' => 'https://www.lapampa.com/images/restaurant2.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example13',
            'google_maps' => 'https://www.google.com/maps/place/Restaurante+La+Pampa',
            'latitude' => 6.2544,
            'longitude' => -75.5731,
            'phone_number' => '1122334455',
            'email' => 'info@lapampa.com',
            'website' => 'https://www.lapampa.com',
            'average_price' => 60.00,
            'menu' => json_encode(['plato1' => 'Asado de Tira', 'plato2' => 'Chorizo']),
            'services' => json_encode(['Delivery', 'Reservas']),
            'category' => 'restaurant',
            'rating' => 4.2,
        ],
        [
            
            'name' => 'Oci.Mde',
            'description' => 'Restaurante moderno que combina gastronomía local con un toque contemporáneo.',
            'location' => 'Medellín',
            'climate' => 'Templado',
            'image_url' => 'https://www.ocimde.com/images/restaurant.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example14',
            'google_maps' => 'https://www.google.com/maps/place/Oci.Mde',
            'latitude' => 6.2450,
            'longitude' => -75.5900,
            'phone_number' => '2233445566',
            'email' => 'info@ocimde.com',
            'website' => 'https://www.ocimde.com',
            'average_price' => 70.00,
            'menu' => json_encode(['plato1' => 'Risotto', 'plato2' => 'Tacos de Pescado']),
            'services' => json_encode(['Reservas']),
            'category' => 'restaurant',
            'rating' => 4.6,
        ],
        [
            
            'name' => 'Café Zorba',
            'description' => 'Café-restaurant famoso por sus pizzas y ambiente bohemio.',
            'location' => 'Medellín',
            'climate' => 'Templado',
            'image_url' => 'https://www.cafezorba.com/images/restaurant.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example15',
            'google_maps' => 'https://www.google.com/maps/place/Café+Zorba',
            'latitude' => 6.2505,
            'longitude' => -75.5750,
            'phone_number' => '3344556677',
            'email' => 'info@cafezorba.com',
            'website' => 'https://www.cafezorba.com',
            'average_price' => 25.00,
            'menu' => json_encode(['plato1' => 'Pizza Margarita', 'plato2' => 'Ensalada Zorba']),
            'services' => json_encode(['Wi-Fi', 'Delivery']),
            'category' => 'café',
            'rating' => 4.3,
        ],
        [
            
            'name' => 'La Pampa Parrilla Argentina',
            'description' => 'Parrilla argentina conocida por sus carnes a la brasa.',
            'location' => 'Medellín',
            'climate' => 'Templado',
            'image_url' => 'https://www.lapampa.com.co/images/restaurant.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example16',
            'google_maps' => 'https://www.google.com/maps/place/La+Pampa+Parrilla+Argentina',
            'latitude' => 6.2480,
            'longitude' => -75.5780,
            'phone_number' => '4455667788',
            'email' => 'info@lapampaparrilla.com',
            'website' => 'https://www.lapampa.com.co',
            'average_price' => 70.00,
            'menu' => json_encode(['plato1' => 'Bife de Chorizo', 'plato2' => 'Provoleta']),
            'services' => json_encode(['Delivery', 'Reservas']),
            'category' => 'restaurant',
            'rating' => 4.4,
        ],
        [
            
            'name' => 'Carmen',
            'description' => 'Restaurante galardonado que combina la cocina colombiana con técnicas modernas.',
            'location' => 'Medellín',
            'climate' => 'Templado',
            'image_url' => 'https://www.carmenmedellin.com/images/restaurant.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example17',
            'google_maps' => 'https://www.google.com/maps/place/Carmen',
            'latitude' => 6.2400,
            'longitude' => -75.5905,
            'phone_number' => '5566778899',
            'email' => 'info@carmenmedellin.com',
            'website' => 'https://www.carmenmedellin.com',
            'average_price' => 90.00,
            'menu' => json_encode(['plato1' => 'Ceviche', 'plato2' => 'Filete de Pescado']),
            'services' => json_encode(['Reservas']),
            'category' => 'restaurant',
            'rating' => 4.8,
        ],
        [
            
            'name' => 'El Herbario',
            'description' => 'Restaurante que ofrece una experiencia gastronómica saludable y orgánica.',
            'location' => 'Medellín',
            'climate' => 'Templado',
            'image_url' => 'https://www.elherbario.com/images/restaurant.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example18',
            'google_maps' => 'https://www.google.com/maps/place/El+Herbario',
            'latitude' => 6.2535,
            'longitude' => -75.5800,
            'phone_number' => '6677889900',
            'email' => 'info@elherbario.com',
            'website' => 'https://www.elherbario.com',
            'average_price' => 40.00,
            'menu' => json_encode(['plato1' => 'Ensalada de Quinoa', 'plato2' => 'Tazón de Frutas']),
            'services' => json_encode(['Delivery']),
            'category' => 'restaurant',
            'rating' => 4.7,
        ],


    //  Mejores Eventos desde festvales feras concertos de musca 
            
        [
            
            'name' => 'Feria de las Flores',
            'description' => 'Evento anual que celebra la cultura antioqueña con desfiles y flores.',
            'location' => 'Medellín',
            'climate' => 'Tropical',
            'image_url' => 'https://www.feriadelasflores.com/images/event1.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example51',
            'google_maps' => 'https://www.google.com/maps/place/Feria+de+las+Flores',
            'latitude' => 6.25184,
            'longitude' => -75.56359,
            'category' => 'event'
        ],
        [
            
            'name' => 'Festival Internacional de Tango',
            'description' => 'Festival que celebra la música y danza del tango.',
            'date' => '2024-06-01',
            'location' => 'Medellín',
            'image_url' => 'https://www.festivaltango.com/images/event2.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example52',
            'google_maps' => 'https://www.google.com/maps/place/Festival+Internacional+de+Tango',
            'latitude' => 6.24722,
            'longitude' => -75.57434,
            'category' => 'event'
        ],
        [
            
            'name' => 'Festival de Cine de Medellín',
            'description' => 'Exhibición de películas nacionales e internacionales.',
            'date' => '2024-10-10',
            'location' => 'Medellín',
            'image_url' => 'https://www.festivaldecinemedellin.com/images/event3.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example53',
            'google_maps' => 'https://www.google.com/maps/place/Festival+de+Cine+de+Medellín',
            'latitude' => 6.26444,
            'longitude' => -75.5675,
            'category' => 'event'
        ],
        [
            
            'name' => 'Feria del Libro',
            'description' => 'Feria anual que celebra la literatura y la cultura.',
            'date' => '2024-09-15',
            'location' => 'Medellín',
            'image_url' => 'https://www.feriadellibro.com/images/event5.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example55',
            'google_maps' => 'https://www.google.com/maps/place/Feria+del+Libro',
            'latitude' => 6.217,
            'longitude' => -75.5702,
            'category' => 'event'
        ],
        [
            
            'name' => 'Festival de Música Clásica',
            'description' => 'Conciertos de música clásica en diferentes escenarios.',
            'date' => '2024-11-20',
            'location' => 'Medellín',
            'image_url' => 'https://www.festivalmusica.com/images/event6.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example56',
            'google_maps' => 'https://www.google.com/maps/place/Festival+de+M%C3%BAsica+Cl%C3%A1sica',
            'latitude' => 6.2459,
            'longitude' => -75.5635,
            'category' => 'event'
        ],
        [
            
            'name' => 'Feria de Antigüedades',
            'description' => 'Exposición y venta de antigüedades y coleccionables.',
            'date' => '2024-05-15',
            'location' => 'Medellín',
            'image_url' => 'https://www.feriadeantiguedades.com/images/event7.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example57',
            'google_maps' => 'https://www.google.com/maps/place/Feria+de+Antig%C3%BCedades',
            'latitude' => 6.253,
            'longitude' => -75.5718,
            'category' => 'event'
        ],
        [
            
            'name' => 'Encuentro de Gastronomía',
            'description' => 'Festival que celebra la cocina colombiana.',
            'date' => '2024-04-25',
            'location' => 'Medellín',
            'image_url' => 'https://www.encuentrogastronomia.com/images/event8.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example58',
            'google_maps' => 'https://www.google.com/maps/place/Encuentro+de+Gastronom%C3%ADa',
            'latitude' => 6.2607,
            'longitude' => -75.5855,
            'category' => 'event'
        ],
        [
            
            'name' => 'Concierto de Música Popular',
            'description' => 'Conciertos de artistas locales y nacionales.',
            'date' => '2024-03-05',
            'location' => 'Medellín',
            'image_url' => 'https://www.conciertomusica.com/images/event9.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example59',
            'google_maps' => 'https://www.google.com/maps/place/Concierto+de+M%C3%BAsica+Popular',
            'latitude' => 6.2751,
            'longitude' => -75.5763,
            'category' => 'event'
        ],
        [
            
            'name' => 'Semana Santa en Medellín',
            'description' => 'Celebraciones y actividades durante la Semana Santa.',
            'date' => '2024-03-28',
            'location' => 'Medellín',
            'image_url' => 'https://www.semanasanta.com/images/event10.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example60',
            'google_maps' => 'https://www.google.com/maps/place/Semana+Santa+en+Medell%C3%ADn',
            'latitude' => 6.2907,
            'longitude' => -75.5746,
            'category' => 'event'
        ],
        [
            
            'name' => 'Festival Internacional de Jazz',
            'description' => 'Celebración de la música jazz con artistas internacionales.',
            'date' => '2024-10-15',
            'location' => 'Medellín',
            'image_url' => 'https://www.festivaljazz.com/images/event2.jpg',
            'google_maps' => 'https://www.google.com/maps/place/Festival+Internacional+de+Jazz',
            'latitude' => 6.2678,
            'longitude' => -75.5731,
            'category' => 'event'
        ],
        [
            
            'name' => 'Concierto de Música Clásica',
            'description' => 'Presentación de una orquesta en el Parque de los Deseos.',
            'date' => '2024-11-20',
            'location' => 'Medellín',
            'image_url' => 'https://www.conciertomusica.com/images/event4.jpg',
            'google_maps' => 'https://www.google.com/maps/place/Concierto+de+M%C3%BAsica+Cl%C3%A1sica',
            'latitude' => 6.2702,
            'longitude' => -75.5709,
            'category' => 'event'
        ],
        [
            'name' => 'Festival de Gastronomía',
            'description' => 'Evento que celebra la comida típica de la región.',
            'date' => '2024-09-10',
            'location' => 'Medellín',
            'image_url' => 'https://www.festivalgastronomia.com/images/event5.jpg',
            'google_maps' => 'https://www.google.com/maps/place/Festival+de+Gastronom%C3%ADa',
            'latitude' => 6.2383,
            'longitude' => -75.5721,
            'category' => 'event'
        ],
        [
        
            'name' => 'Feria del Café',
            'description' => 'Evento que destaca la cultura cafetera de la región.',
            'date' => '2024-06-01',
            'location' => 'Manizales',
            'image_url' => 'https://www.feriadelcafe.com/images/event7.jpg',
            'google_maps' => 'https://www.google.com/maps/place/Feria+del+Caf%C3%A9',
            'latitude' => 5.0703,
            'longitude' => -75.5138,
            'category' => 'event'
        ],

                //  Mejores Lugares Culturales Museos y teatros 
            
        [
            
            'name' => 'Museo de Antioquia',
            'description' => 'Museo con una rica colección de arte moderno y contemporáneo.',
            'location' => 'Medellín',
            'image_url' => 'https://www.museodeantioquia.com/images/culture1.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example61',
            'google_maps' => 'https://www.google.com/maps/place/Museo+de+Antioquia',
            'latitude' => 6.2442,
            'longitude' => -75.5736,
            'event_date' => null,
            'category' => 'Cultura',
            'activities' => json_encode(['Visitas guiadas', 'Talleres de arte']),
            'duration_days' => null,
            'artists' => json_encode(['Fernando Botero', 'Débora Arango']),
            'contact_info' => 'Tel: (604) 251 3636',
            'website' => 'https://www.museodeantioquia.com'
        ],
        [
            
            'name' => 'Teatro Metropolitano',
            'description' => 'Espacio cultural para presentaciones de teatro y música.',
            'location' => 'Medellín',
            'image_url' => 'https://www.teatrometropolitano.com/images/culture2.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example62',
            'google_maps' => 'https://www.google.com/maps/place/Teatro+Metropolitano',
            'latitude' => 6.2443,
            'longitude' => -75.5737,
            'event_date' => null,
            'category' => 'Cultura',
            'activities' => json_encode(['Obras de teatro', 'Conciertos']),
            'duration_days' => null,
            'artists' => json_encode(['Grupo de Teatro de Medellín']),
            'contact_info' => 'Tel: (604) 232 1490',
            'website' => 'https://www.teatrometropolitano.com'
        ],
        [
        
            'name' => 'Parque Explora',
            'description' => 'Centro interactivo de ciencia y tecnología.',
            'location' => 'Medellín',
            'image_url' => 'https://www.parqueexplora.com/images/culture3.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example63',
            'google_maps' => 'https://www.google.com/maps/place/Parque+Explora',
            'latitude' => 6.2546,
            'longitude' => -75.5865,
            'event_date' => null,
            'category' => 'Cultura',
            'activities' => json_encode(['Exposiciones interactivas', 'Talleres científicos']),
            'duration_days' => null,
            'artists' => json_encode([]),
            'contact_info' => 'Tel: (604) 444 4343',
            'website' => 'https://www.parqueexplora.com',
        ],
        [
            
            'name' => 'Casa de la Memoria',
            'description' => 'Espacio dedicado a la memoria histórica de Medellín.',
            'location' => 'Medellín',
            'image_url' => 'https://www.casadelamemoria.com/images/culture4.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example64',
            'google_maps' => 'https://www.google.com/maps/place/Casa+de+la+Memoria',
            'latitude' => 6.2527,
            'longitude' => -75.5784,
            'event_date' => null,
            'category' => 'Cultura',
            'activities' => json_encode(['Visitas guiadas', 'Charlas sobre memoria histórica']),
            'duration_days' => null,
            'artists' => json_encode([]),
            'contact_info' => 'Tel: (604) 444 1212',
            'website' => 'https://www.casadelamemoria.com'
        ],
        [
            
            'name' => 'Museo de Arte Moderno',
            'description' => 'Exposición de obras de arte moderno y contemporáneo.',
            'location' => 'Medellín',
            'image_url' => 'https://www.mam.com.co/images/culture5.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example65',
            'google_maps' => 'https://www.google.com/maps/place/Museo+de+Arte+Moderno',
            'latitude' => 6.2440,
            'longitude' => -75.5729,
            'event_date' => null,
            'category' => 'Cultura',
            'activities' => json_encode(['Exposiciones temporales', 'Talleres de arte']),
            'duration_days' => null,
            'artists' => json_encode(['Francisco Antonio Cano']),
            'contact_info' => 'Tel: (604) 444 6044',
            'website' => 'https://www.mam.com.co'
        ],
        [
            
            'name' => 'Pueblito Paisa',
            'description' => 'Recreación de un pueblo tradicional antioqueño.',
            'location' => 'Medellín',
            'image_url' => 'https://www.pueblitopaisa.com/images/culture6.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example66',
            'google_maps' => 'https://www.google.com/maps/place/Pueblito+Paisa',
            'latitude' => 6.2322,
            'longitude' => -75.5702,
            'event_date' => null,
            'category' => 'Cultura',
            'activities' => json_encode(['Recorridos culturales', 'Actividades para niños']),
            'duration_days' => null,
            'artists' => json_encode([]),
            'contact_info' => 'Tel: (604) 232 3801',
            'website' => 'https://www.pueblitopaisa.com'
        ],
        [
            
            'name' => 'El Castillo Museo y Jardines',
            'description' => 'Castillo histórico con hermosos jardines y exposiciones.',
            'location' => 'Medellín',
            'image_url' => 'https://www.elcastillo.com/images/culture7.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example67',
            'google_maps' => 'https://www.google.com/maps/place/El+Castillo+Museo+y+Jardines',
            'latitude' => 6.2373,
            'longitude' => -75.5888,
            'event_date' => null,
            'category' => 'Cultura',
            'activities' => json_encode(['Visitas guiadas', 'Eventos culturales']),
            'duration_days' => null,
            'artists' => json_encode([]),
            'contact_info' => 'Tel: (604) 268 1448',
            'website' => 'https://www.elcastillo.com'
        ],
        [
            
            'name' => 'Museo del Oro',
            'description' => 'Museo que exhibe la historia del oro en Colombia.',
            'location' => 'Medellín',
            'image_url' => 'https://www.museodeloro.com/images/culture8.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example68',
            'google_maps' => 'https://www.google.com/maps/place/Museo+del+Oro',
            'latitude' => 6.2519,
            'longitude' => -75.5705,
            'event_date' => null,
            'category' => 'Cultura',
            'activities' => json_encode(['Exhibiciones de oro', 'Talleres']),
            'duration_days' => null,
            'artists' => json_encode([]),
            'contact_info' => 'Tel: (604) 570 0000',
            'website' => 'https://www.museodeloro.com'
        ],

    [
        
        'name' => 'Centro Cultural Palacio de la Cultura',
        'description' => 'Espacio para exposiciones culturales y artísticas.',
        'location' => 'Medellín',
        'image_url' => 'https://www.centrocultural.com/images/culture9.jpg',
        'video_url' => 'https://www.youtube.com/watch?v=example69',
        'google_maps' => 'https://www.google.com/maps/place/Centro+Cultural+Palacio+de+la+Cultura',
        'latitude' => 6.2442,
        'longitude' => -75.5740,
        'event_date' => null,
        'category' => 'Cultura',
        'activities' => json_encode(['Exposiciones', 'Talleres']),
        'duration_days' => null,
        'artists' => json_encode([]),
        'contact_info' => 'Tel: (604) 280 0000, Email: info@centrocultural.com',
        'website' => 'https://www.centrocultural.com'// Asegúrate de incluir la URL del sitio web
    ],
        [ 
            'name' => 'Festival Internacional de Jazz',
            'description' => 'Un evento anual que celebra la música jazz con artistas nacionales e internacionales.',
            'location' => 'Medellín',
            'image_url' => 'https://www.festivaljazz.com/images/jazz-festival.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example1',
            'google_maps' => 'https://www.google.com/maps/place/Festival+Internacional+de+Jazz',
            'latitude' => 6.2519,
            'longitude' => -75.5703,
            'event_date' => '2024-07-01',
            'category' => 'cultura',
            'activities' => json_encode(['Conciertos', 'Talleres de música']),
            'duration_days' => 3,
            'artists' => json_encode(['Artistas internacionales']),
            'contact_info' => 'Tel: (604) 300 0000',
            'website' => 'https://www.festivaljazz.com'
        ],
        [      
            'name' => 'Feria de las Flores',
            'description' => 'Celebración de la cultura paisa y sus flores en Medellín.',
            'location' => 'Medellín',
            'image_url' => 'https://www.feriadelasflores.com/images/feria.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example2',
            'google_maps' => 'https://www.google.com/maps/place/Feria+de+las+Flores',
            'latitude' => 6.2450,
            'longitude' => -75.5900,
            'event_date' => '2024-08-02',
            'category' => 'Cultura',
            'activities' => json_encode(['Desfile de silleteros', 'Conciertos']),
            'duration_days' => 10,
            'artists' => json_encode(['Artistas locales']),
            'contact_info' => 'Tel: (604) 260 0000',
            'website' => 'https://www.feriadelasflores.com'
        ],
        [
            'name' => 'Fiesta de la Música',
            'description' => 'Un evento donde la música se apodera de las calles de Medellín.',
            'location' => 'Medellín',
            'image_url' => 'https://www.fiestadelamusica.com/images/fiesta.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example3',
            'google_maps' => 'https://www.google.com/maps/place/Fiesta+de+la+Musica',
            'latitude' => 6.2500,
            'longitude' => -75.5705,
            'event_date' => '2024-06-21',
            'category' => 'Cultura',
            'activities' => json_encode(['Conciertos gratuitos', 'Actividades para niños']),
            'duration_days' => 1,
            'artists' => json_encode(['Músicos locales']),
            'contact_info' => 'Tel: (604) 400 0000',
            'website' => 'https://www.fiestadelamusica.com'
        ],
        [
            'name' => 'Cine en las Montañas',
            'description' => 'Proyecciones de cine al aire libre en diferentes localidades de Antioquia.',
            'location' => 'Antioquia',
            'image_url' => 'https://www.cineenlasmontanas.com/images/cine.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example4',
            'google_maps' => 'https://www.google.com/maps/place/Cine+en+las+Montañas',
            'latitude' => 6.2422,
            'longitude' => -75.5865,
            'event_date' => '2024-07-15',
            'category' => 'Cultura',
            'activities' => json_encode(['Proyecciones de películas', 'Charlas con directores']),
            'duration_days' => 5,
            'artists' => json_encode(['Directores de cine locales']),
            'contact_info' => 'Tel: (604) 250 0000',
            'website' => 'https://www.cineenlasmontanas.com'
        ],

        [
            'name' => 'Festival del Libro y la Cultura',
            'description' => 'Un evento literario que reúne a escritores y amantes de los libros.',
            'location' => 'Medellín',
            'image_url' => 'https://www.festivaldelibro.com/images/libro.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example5',
            'google_maps' => 'https://www.google.com/maps/place/Festival+del+Libro+y+la+Cultura',
            'latitude' => 6.2400,
            'longitude' => -75.5700,
            'event_date' => '2024-09-01',
            'category' => 'Cultura',
            'activities' => json_encode(['Firmas de libros', 'Charlas y talleres']),
            'duration_days' => 7,
            'artists' => json_encode(['Escritores colombianos']),
            'contact_info' => 'Tel: (604) 600 0000',
            'website' => 'https://www.festivaldelibro.com'
        ],

        [
            'name' => 'Festival Internacional de Jazz',
            'description' => 'Un evento anual que celebra la música jazz con artistas nacionales e internacionales.',
            'location' => 'Medellín',
            'image_url' => 'https://www.festivaljazz.com/images/jazz-festival.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example1',
            'google_maps' => 'https://www.google.com/maps/place/Festival+Internacional+de+Jazz',
            'latitude' => 6.2519,
            'longitude' => -75.5703,
            'event_date' => '2024-07-01',
            'category' => 'Festival',
            'activities' => json_encode(['Conciertos', 'Talleres de música']),
            'duration_days' => 3,
            'artists' => json_encode(['Artistas internacionales']),
            'contact_info' => 'Tel: (604) 300 0000',
            'website' => 'https://www.festivaljazz.com'
        ],
        [
            'name' => 'Feria de las Flores',
            'description' => 'Celebración de la cultura paisa y sus flores en Medellín.',
            'location' => 'Medellín',
            'image_url' => 'https://www.feriadelasflores.com/images/feria.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example2',
            'google_maps' => 'https://www.google.com/maps/place/Feria+de+las+Flores',
            'latitude' => 6.2450,
            'longitude' => -75.5900,
            'event_date' => '2024-08-02',
            'category' => 'Cultura',
            'activities' => json_encode(['Desfile de silleteros', 'Conciertos']),
            'duration_days' => 10,
            'artists' => json_encode(['Artistas locales']),
            'contact_info' => 'Tel: (604) 260 0000',
            'website' => 'https://www.feriadelasflores.com'
        ],
        [
            'name' => 'Fiesta de la Música',
            'description' => 'Un evento donde la música se apodera de las calles de Medellín.',
            'location' => 'Medellín',
            'image_url' => 'https://www.fiestadelamusica.com/images/fiesta.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example3',
            'google_maps' => 'https://www.google.com/maps/place/Fiesta+de+la+Musica',
            'latitude' => 6.2500,
            'longitude' => -75.5705,
            'event_date' => '2024-06-21',
            'category' => 'Música',
            'activities' => json_encode(['Conciertos gratuitos', 'Actividades para niños']),
            'duration_days' => 1,
            'artists' => json_encode(['Músicos locales']),
            'contact_info' => 'Tel: (604) 400 0000',
            'website' => 'https://www.fiestadelamusica.com'
        ],
        [
            'name' => 'Cine en las Montañas',
            'description' => 'Proyecciones de cine al aire libre en diferentes localidades de Antioquia.',
            'location' => 'Antioquia',
            'image_url' => 'https://www.cineenlasmontanas.com/images/cine.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example4',
            'google_maps' => 'https://www.google.com/maps/place/Cine+en+las+Montañas',
            'latitude' => 6.2422,
            'longitude' => -75.5865,
            'event_date' => '2024-07-15',
            'category' => 'Cine',
            'activities' => json_encode(['Proyecciones de películas', 'Charlas con directores']),
            'duration_days' => 5,
            'artists' => json_encode(['Directores de cine locales']),
            'contact_info' => 'Tel: (604) 250 0000',
            'website' => 'https://www.cineenlasmontanas.com'
        ],
        [
            'name' => 'Festival del Libro y la Cultura',
            'description' => 'Un evento literario que reúne a escritores y amantes de los libros.',
            'location' => 'Medellín',
            'image_url' => 'https://www.festivaldelibro.com/images/libro.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example5',
            'google_maps' => 'https://www.google.com/maps/place/Festival+del+Libro+y+la+Cultura',
            'latitude' => 6.2400,
            'longitude' => -75.5700,
            'event_date' => '2024-09-01',
            'category' => 'Cultura',
            'activities' => json_encode(['Firmas de libros', 'Charlas y talleres']),
            'duration_days' => 7,
            'artists' => json_encode(['Escritores colombianos']),
            'contact_info' => 'Tel: (604) 600 0000',
            'website' => 'https://www.festivaldelibro.com'
        ],
    // Mejores Artesanías talleres y lugares 

    
        [
            
            'name' => 'Artesanías de Guatapé',
            'description' => 'Artesanías coloridas y únicas hechas a mano en Guatapé.',
            'location' => 'Guatapé',
            'image_url' => 'https://www.artesaniasguatape.com/images/crafts1.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example71',
            'google_maps' => 'https://www.google.com/maps/place/Artesanías+de+Guatapé',
            'material' => 'Madera, Barro',
            'technique' => 'Técnica de alfarería',
            'price' => 25.00,
            'categories' => json_encode(['decoración', 'útiles']),
            'artist' => 'Artisan Name 1',
            'contact_info' => 'Tel: (604) 123 4567, Email: info@artesaniasguatape.com',
        ],
        [
            
            'name' => 'Sombreros Vueltiaos',
            'description' => 'Sombreros tradicionales de la región de Sucre, elaborados a mano.',
            'location' => 'Sucre',
            'image_url' => 'https://www.example.com/images/sombrero1.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example72',
            'google_maps' => 'https://www.google.com/maps/place/Sombreros+Vueltiaos',
            'material' => 'Paja',
            'technique' => 'Tejido manual',
            'price' => 40.00,
            'categories' => json_encode(['moda', 'tradicional']),
            'artist' => 'Artisan Name 2',
            'contact_info' => 'Tel: (604) 234 5678, Email: info@sombreros.com',
        ],
        [
            
            'name' => 'Cerámica de Ráquira',
            'description' => 'Cerámicas coloridas y utilitarias de la región de Ráquira.',
            'location' => 'Ráquira',
            'image_url' => 'https://www.example.com/images/ceramica1.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example73',
            'google_maps' => 'https://www.google.com/maps/place/Cerámica+de+Ráquira',
            'material' => 'Barro',
            'technique' => 'Alfarería',
            'price' => 35.00,
            'categories' => json_encode(['decoración', 'útiles']),
            'artist' => 'Artisan Name 3',
            'contact_info' => 'Tel: (604) 345 6789, Email: info@ceramicarquira.com',
        ],
        [
            
            'name' => 'Mochilas Wayuu',
            'description' => 'Mochilas tejidas a mano por la comunidad Wayuu.',
            'location' => 'La Guajira',
            'image_url' => 'https://www.example.com/images/mochila1.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example74',
            'google_maps' => 'https://www.google.com/maps/place/Mochilas+Wayuu',
            'material' => 'Hilo',
            'technique' => 'Tejido a mano',
            'price' => 50.00,
            'categories' => json_encode(['moda', 'artesanal']),
            'artist' => 'Artisan Name 4',
            'contact_info' => 'Tel: (604) 456 7890, Email: info@mochilaswayuu.com',
        ],
        [
            
            'name' => 'Cojines de Café',
            'description' => 'Cojines artesanales hechos con sacos de café reciclados.',
            'location' => 'Eje Cafetero',
            'image_url' => 'https://www.example.com/images/cojin1.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example75',
            'google_maps' => 'https://www.google.com/maps/place/Cojines+de+Café',
            'material' => 'Tela reciclada',
            'technique' => 'Costura',
            'price' => 30.00,
            'categories' => json_encode(['decoración', 'reciclaje']),
            'artist' => 'Artisan Name 5',
            'contact_info' => 'Tel: (604) 567 8901, Email: info@cojinesdecafe.com',
        ],
        [
            
            'name' => 'Muebles de Palets',
            'description' => 'Muebles rústicos y ecológicos elaborados con palets reciclados.',
            'location' => 'Bogotá',
            'image_url' => 'https://www.example.com/images/mueble1.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example76',
            'google_maps' => 'https://www.google.com/maps/place/Muebles+de+Palets',
            'material' => 'Madera reciclada',
            'technique' => 'Construcción manual',
            'price' => 150.00,
            'categories' => json_encode(['muebles', 'reciclaje']),
            'artist' => 'Artisan Name 6',
            'contact_info' => 'Tel: (604) 678 9012, Email: info@mueblesdepalets.com',
        ],
        [
            
            'name' => 'Bolsos de Tela',
            'description' => 'Bolsos ecológicos hechos de tela reciclada y técnicas de bordado.',
            'location' => 'Cali',
            'image_url' => 'https://www.example.com/images/bolso1.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example77',
            'google_maps' => 'https://www.google.com/maps/place/Bolsos+de+Tela',
            'material' => 'Tela reciclada',
            'technique' => 'Bordado',
            'price' => 20.00,
            'categories' => json_encode(['moda', 'reciclaje']),
            'artist' => 'Artisan Name 7',
            'contact_info' => 'Tel: (604) 789 0123, Email: info@bolsostela.com',
        ],
        [
            
            'name' => 'Joyas de Arcilla',
            'description' => 'Joyas únicas y artesanales hechas de arcilla polimérica.',
            'location' => 'Medellín',
            'image_url' => 'https://www.example.com/images/joya1.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example78',
            'google_maps' => 'https://www.google.com/maps/place/Joyas+de+Arcilla',
            'material' => 'Arcilla polimérica',
            'technique' => 'Modelado a mano',
            'price' => 15.00,
            'categories' => json_encode(['joyería', 'artesanal']),
            'artist' => 'Artisan Name 8',
            'contact_info' => 'Tel: (604) 890 1234, Email: info@joyasdearcilla.com',
        ],
        [
            
            'name' => 'Cestas de Mimbre',
            'description' => 'Cestas tejidas a mano con técnica tradicional de mimbre.',
            'location' => 'Santander',
            'image_url' => 'https://www.example.com/images/cesta1.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example79',
            'google_maps' => 'https://www.google.com/maps/place/Cestas+de+Mimbre',
            'material' => 'Mimbre',
            'technique' => 'Tejido a mano',
            'price' => 45.00,
            'categories' => json_encode(['decoración', 'útiles']),
            'artist' => 'Artisan Name 9',
            'contact_info' => 'Tel: (604) 901 2345, Email: info@cestasdemimbre.com',
        ],
        [
            
            'name' => 'Figuras de Guatapé',
            'description' => 'Figuras artesanales pintadas a mano representando la cultura de Guatapé.',
            'location' => 'Guatapé',
            'image_url' => 'https://www.example.com/images/figura1.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example80',
            'google_maps' => 'https://www.google.com/maps/place/Figuras+de+Guatapé',
            'material' => 'Madera',
            'technique' => 'Pintura a mano',
            'price' => 30.00,
            'categories' => json_encode(['decoración', 'arte']),
            'artist' => 'Artisan Name 10',
            'contact_info' => 'Tel: (604) 012 3456, Email: info@figurasdeguatape.com',
        ],


        [
            
            'name' => 'Centro Comercial El Tesoro',
            'description' => 'Centro comercial con diversas tiendas y entretenimiento.',
            'location' => 'Medellín',
            'climate' => 'Tropical',
            'image_url' => 'https://www.eltesorocomercial.com/images/mall1.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example41',
            'google_maps' => 'https://www.google.com/maps/place/Centro+Comercial+El+Tesoro',
            'category' => 'commerce',
            'contact_number' => '(604) 123 4567',
            'email' => 'info@eltesorocomercial.com',
            'website' => 'https://www.eltesorocomercial.com',
            'categories' => json_encode(['centro comercial', 'entretenimiento']),
        ],
        [
            
            'name' => 'La 70',
            'description' => 'Zona de comercio y entretenimiento con una variedad de tiendas y restaurantes.',
            'location' => 'Medellín',
            'climate' => 'Templado',
            'image_url' => 'https://www.la70.com/images/comercio.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example42',
            'google_maps' => 'https://www.google.com/maps/place/La+70',
            'category' => 'commerce',
            'contact_number' => '(604) 234 5678',
            'email' => 'info@la70.com',
            'website' => 'https://www.la70.com',
            'categories' => json_encode(['zona comercial', 'entretenimiento']),
        ],
        [
            
            'name' => 'Centro Comercial Santafé',
            'description' => 'Uno de los centros comerciales más grandes de Medellín con múltiples opciones de compras.',
            'location' => 'Medellín',
            'climate' => 'Templado',
            'image_url' => 'https://www.santafe.com.co/images/comercio.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example43',
            'google_maps' => 'https://www.google.com/maps/place/Centro+Comercial+Santafé',
            'category' => 'commerce',
            'contact_number' => '(604) 345 6789',
            'email' => 'info@santafe.com.co',
            'website' => 'https://www.santafe.com.co',
            'categories' => json_encode(['centro comercial', 'compras']),
        ],
        [
        
            'name' => 'Plaza Mayor',
            'description' => 'Centro de exposiciones y convenciones con tiendas y servicios.',
            'location' => 'Medellín',
            'climate' => 'Templado',
            'image_url' => 'https://www.plazamayor.com.co/images/comercio.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example44',
            'google_maps' => 'https://www.google.com/maps/place/Plaza+Mayor',
            'category' => 'commerce',
            'contact_number' => '(604) 456 7890',
            'email' => 'info@plazamayor.com.co',
            'website' => 'https://www.plazamayor.com.co',
            'categories' => json_encode(['exposiciones', 'servicios']),
        ],
        [
            
            'name' => 'Mercado del Rio',
            'description' => 'Un espacio gastronómico con opciones de comida local e internacional.',
            'location' => 'Medellín',
            'climate' => 'Templado',
            'image_url' => 'https://www.mercadodelrio.com.co/images/comercio.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example45',
            'google_maps' => 'https://www.google.com/maps/place/Mercado+del+Rio',
            'category' => 'commerce',
            'contact_number' => '(604) 567 8901',
            'email' => 'info@mercadodelrio.com.co',
            'website' => 'https://www.mercadodelrio.com.co',
            'categories' => json_encode(['gastronomía', 'comida']),
        ],
        [
            
            'name' => 'La Playa Centro Comercial',
            'description' => 'Centro comercial que ofrece una variedad de tiendas y servicios.',
            'location' => 'Medellín',
            'climate' => 'Templado',
            'image_url' => 'https://www.laplaya.com.co/images/comercio.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example46',
            'google_maps' => 'https://www.google.com/maps/place/La+Playa+Centro+Comercial',
            'category' => 'commerce',
            'contact_number' => '(604) 678 9012',
            'email' => 'info@laplaya.com.co',
            'website' => 'https://www.laplaya.com.co',
            'categories' => json_encode(['centro comercial', 'compras']),
        ],
        [
            
            'name' => 'El Tesoro Parque Comercial',
            'description' => 'Centro comercial con vista panorámica y tiendas exclusivas.',
            'location' => 'Medellín',
            'climate' => 'Templado',
            'image_url' => 'https://www.eltesoroparque.com.co/images/comercio.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example47',
            'google_maps' => 'https://www.google.com/maps/place/El+Tesoro+Parque+Comercial',
            'category' => 'commerce',
            'contact_number' => '(604) 789 0123',
            'email' => 'info@eltesoroparque.com.co',
            'website' => 'https://www.eltesoroparque.com.co',
            'categories' => json_encode(['centro comercial', 'tiendas exclusivas']),
        ],
        [
            
            'name' => 'Centro Comercial Oviedo',
            'description' => 'Espacio comercial con una variedad de opciones de entretenimiento y compras.',
            'location' => 'Medellín',
            'climate' => 'Templado',
            'image_url' => 'https://www.oviedo.com.co/images/comercio.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example48',
            'google_maps' => 'https://www.google.com/maps/place/Centro+Comercial+Oviedo',
            'category' => 'commerce',
            'contact_number' => '(604) 890 1234',
            'email' => 'info@oviedo.com.co',
            'website' => 'https://www.oviedo.com.co',
            'categories' => json_encode(['centro comercial', 'entretenimiento']),
        ],
        [
            
            'name' => 'La 33',
            'description' => 'Área de comercio local con tiendas de ropa, comida y más.',
            'location' => 'Medellín',
            'climate' => 'Templado',
            'image_url' => 'https://www.la33.com/images/comercio.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example49',
            'google_maps' => 'https://www.google.com/maps/place/La+33',
            'category' => 'commerce',
            'contact_number' => '(604) 901 2345',
            'email' => 'info@la33.com',
            'website' => 'https://www.la33.com',
            'categories' => json_encode(['comercio local', 'tiendas']),
        ],
        [
            
            'name' => 'Centro Comercial Premium Plaza',
            'description' => 'Centro comercial moderno con opciones de entretenimiento y compras.',
            'location' => 'Medellín',
            'climate' => 'Templado',
            'image_url' => 'https://www.premiumplaza.com.co/images/comercio.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example50',
            'google_maps' => 'https://www.google.com/maps/place/Centro+Comercial+Premium+Plaza',
            'category' => 'commerce',
            'contact_number' => '(604) 012 3456',
            'email' => 'info@premiumplaza.com.co',
            'website' => 'https://www.premiumplaza.com.co',
            'categories' => json_encode(['centro comercial', 'entretenimiento']),
        ],
        [
            
            'name' => 'Mall Plaza',
            'description' => 'Centro comercial con una gran variedad de tiendas y actividades familiares.',
            'location' => 'Medellín',
            'climate' => 'Templado',
            'image_url' => 'https://www.mallplaza.com.co/images/comercio.jpg',
            'video_url' => 'https://www.youtube.com/watch?v=example51',
            'google_maps' => 'https://www.google.com/maps/place/Mall+Plaza',
            'category' => 'commerce',
            'contact_number' => '(604) 123 4567',
            'email' => 'info@mallplaza.com.co',
            'website' => 'https://www.mallplaza.com.co',
            'categories' => json_encode(['centro comercial', 'actividades familiares']),
        ],

    //service
                [
                
                    'name' => 'Servicio de Transporte Medellín',
                    'description' => 'Servicio de transporte privado en la ciudad.',
                    'location' => 'Medellín',
                    'image_url' => 'https://www.transporte.com/images/service1.jpg',
                    'video_url' => 'https://www.youtube.com/watch?v=example31',
                    'google_maps' => 'https://www.google.com/maps/place/Servicio+de+Transporte+Medellín',
                    'category' => 'service',
                    'provider_name' => 'Transporte Medellín',
                    'cost' => 10000.00,
                    'duration' => '1 hora',
                    'contact_info' => 'info@transporte.com',
                ],
                [
                    
                    'name' => 'Spa Relax',
                    'description' => 'Centro de relajación y bienestar.',
                    'location' => 'Medellín',
                    'image_url' => 'https://www.sparelax.com/images/service1.jpg',
                    'video_url' => 'https://www.youtube.com/watch?v=example31',
                    'google_maps' => 'https://www.google.com/maps/place/Spa+Relax',
                    'category' => 'service',
                    'provider_name' => 'Spa Relax',
                    'cost' => 50000.00,
                    'duration' => '2 horas',
                    'contact_info' => 'contacto@sparelax.com',
                ],
                [
                    
                    'name' => 'Masajes Terapéuticos',
                    'description' => 'Masajes para aliviar el estrés y la tensión.',
                    'location' => 'Medellín',
                    'image_url' => 'https://www.masajesterapeuticos.com/images/service2.jpg',
                    'google_maps' => 'https://www.google.com/maps/place/Masajes+Terap%C3%A9uticos',
                    'category' => 'service',
                    'provider_name' => 'Masajes Terapéuticos',
                    'cost' => 60000.00,
                    'duration' => '1 hora',
                    'contact_info' => 'info@masajesterapeuticos.com',
                ],
                [
                    
                    'name' => 'Centro de Yoga y Meditación',
                    'description' => 'Clases de yoga y meditación para todos los niveles.',
                    'location' => 'Medellín',
                    'image_url' => 'https://www.centrodemeditacion.com/images/service3.jpg',
                    'google_maps' => 'https://www.google.com/maps/place/Centro+de+Yoga+y+Meditaci%C3%B3n',
                    'category' => 'service',
                    'provider_name' => 'Centro de Yoga',
                    'cost' => 40000.00,
                    'duration' => '1.5 horas',
                    'contact_info' => 'contacto@centrodemeditacion.com',
                ],
                [
                    
                    'name' => 'Salón de Belleza Estilo',
                    'description' => 'Servicios de peluquería y estética.',
                    'location' => 'Medellín',
                    'image_url' => 'https://www.salonestilo.com/images/service4.jpg',
                    'google_maps' => 'https://www.google.com/maps/place/Sal%C3%B3n+de+Belleza+Estilo',
                    'category' => 'service',
                    'provider_name' => 'Salón Estilo',
                    'cost' => 30000.00,
                    'duration' => '2 horas',
                    'contact_info' => 'info@salonestilo.com',
                ],
                [
                    
                    'name' => 'Gimnasio Fitness',
                    'description' => 'Entrenamiento y clases de fitness.',
                    'location' => 'Medellín',
                    'image_url' => 'https://www.gimnasiofitness.com/images/service5.jpg',
                    'google_maps' => 'https://www.google.com/maps/place/Gimnasio+Fitness',
                    'category' => 'service',
                    'provider_name' => 'Gimnasio Fitness',
                    'cost' => 50000.00,
                    'duration' => 'Mensual',
                    'contact_info' => 'info@gimnasiofitness.com',
                ],
                [
                    
                    'name' => 'Centro de Terapia Alternativa',
                    'description' => 'Terapias alternativas para el bienestar físico y mental.',
                    'location' => 'Medellín',
                    'image_url' => 'https://www.centrodeterapiaalternativa.com/images/service6.jpg',
                    'google_maps' => 'https://www.google.com/maps/place/Centro+de+Terapia+Alternativa',
                    'category' => 'service',
                    'provider_name' => 'Centro de Terapia Alternativa',
                    'cost' => 70000.00,
                    'duration' => '1 hora',
                    'contact_info' => 'contacto@centrodeterapiaalternativa.com',
                ],
                [
                    
                    'name' => 'Tienda de Aromaterapia',
                    'description' => 'Productos de aromaterapia para el hogar y la salud.',
                    'location' => 'Medellín',
                    'image_url' => 'https://www.tiendaaromaterapia.com/images/service7.jpg',
                    'google_maps' => 'https://www.google.com/maps/place/Tienda+de+Aromaterapia',
                    'category' => 'service',
                    'provider_name' => 'Tienda de Aromaterapia',
                    'cost' => 25000.00,
                    'duration' => 'N/A',
                    'contact_info' => 'info@tiendaaromaterapia.com',
                ],
                [
                    
                    'name' => 'Peluquería y Estética Glamour',
                    'description' => 'Servicios de peluquería y tratamientos estéticos.',
                    'location' => 'Medellín',
                    'image_url' => 'https://www.peluqueriaestetica.com/images/service8.jpg',
                    'google_maps' => 'https://www.google.com/maps/place/Peluquer%C3%ADa+y+Est%C3%A9tica+Glamour',
                    'category' => 'service',
                    'provider_name' => 'Glamour Estética',
                    'cost' => 35000.00,
                    'duration' => '1.5 horas',
                    'contact_info' => 'info@peluqueriaestetica.com',
                ],
                [
                    
                    'name' => 'Masajes Relajantes',
                    'description' => 'Masajes para liberar tensiones y relajarse.',
                    'location' => 'Medellín',
                    'image_url' => 'https://www.masajesrelajantes.com/images/service9.jpg',
                    'google_maps' => 'https://www.google.com/maps/place/Masajes+Relajantes',
                    'category' => 'service',
                    'provider_name' => 'Masajes Relajantes',
                    'cost' => 60000.00,
                    'duration' => '1 hora',
                    'contact_info' => 'info@masajesrelajantes.com',
                ],
                [
                    
                    'name' => 'Centro de Bienestar Integral',
                    'description' => 'Enfoque holístico en salud y bienestar.',
                    'location' => 'Medellín',
                    'image_url' => 'https://www.centrobienestar.com/images/service10.jpg',
                    'google_maps' => 'https://www.google.com/maps/place/Centro+de+Bienestar+Integral',
                    'category' => 'service',
                    'provider_name' => 'Bienestar Integral',
                    'cost' => 80000.00,
                    'duration' => '1 hora',
                    'contact_info' => 'info@centrobienestar.com',
                ],

    ];
    
            foreach ($places as $place) {
                Place::create($place);
            }
        

            // Inserta los datos en la tabla 'places'
        // DB::table('places')->insert($places);
        }  }
